[build]
 dockerfile = "Dockerfile"

[http_service]
 internal_port = 1314
 force_https = true

[[services]]
 protocol = "tcp"
 internal_port = 1314
 [[services.ports]]
 port = 1314

[[vm]]
 memory = "512mb"
 cpu_kind = "shared"
 cpus = 1
